<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>Images\app_icon.ico</ApplicationIcon>
    <Authors>Initio Team</Authors>
    <Product>Initio</Product>
    <AssemblyTitle>Initio</AssemblyTitle>
    <AssemblyName>Initio</AssemblyName>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishReadyToRun>true</PublishReadyToRun>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="Initio.Core\Initio.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\**" />
    <EmbeddedResource Include="catalog.json" LogicalName="catalog.json" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Tests\**" />
    <Compile Remove="Tests.UI\**" />
    <Compile Remove="Initio.Core\**" />
    <None Remove="Tests\**" />
    <None Remove="Tests.UI\**" />
    <None Remove="Initio.Core\**" />
  </ItemGroup>
</Project>
