// StoreTrendCatalog.cs
// Static catalog of popular FREE apps from Microsoft Store categories.
// Each category provides ~30 well-known, free/freemium apps for discovery.

namespace NewPCSetupWPF.Models;

public static class StoreTrendCatalog
{
    public static IReadOnlyList<StoreTrendItem> CreateDefault()
    {
        var items = new List<StoreTrendItem>(200);

        items.AddRange(BuildCategory("Productivity",
            ("Microsoft PowerToys", "Microsoft.PowerToys"),
            ("7-Zip", "7zip.7zip"),
            ("Notepad++", "Notepad++.Notepad++"),
            ("LibreOffice", "TheDocumentFoundation.LibreOffice"),
            ("Foxit PDF Reader", "Foxit.FoxitReader"),
            ("Dropbox", "Dropbox.Dropbox"),
            ("Google Drive", "Google.Drive"),
            ("OneDrive", "Microsoft.OneDrive"),
            ("Obsidian", "Obsidian.Obsidian"),
            ("Notion", "Notion.Notion"),
            ("Todoist", "Doist.Todoist"),
            ("TickTick", "Appest.TickTick"),
            ("Files", "FilesCommunity.Files"),
            ("EarTrumpet", "File-New-Project.EarTrumpet"),
            ("NanaZip", "M2Team.NanaZip"),
            ("Everything", "voidtools.Everything"),
            ("ShareX", "ShareX.ShareX"),
            ("CrystalDiskInfo", "CrystalDewWorld.CrystalDiskInfo"),
            ("Bitwarden", "Bitwarden.Bitwarden"),
            ("KeePassXC", "KeePassXCTeam.KeePassXC"),
            ("AutoHotKey v2", "AutoHotkey.AutoHotkey"),
            ("Flow Launcher", "Flow-Launcher.Flow-Launcher"),
            ("QuickLook", "QL-Win.QuickLook"),
            ("WinDirStat", "WinDirStat.WinDirStat"),
            ("Greenshot", "Greenshot.Greenshot"),
            ("Ditto", "Ditto.Ditto"),
            ("Twinkle Tray", "xanderfrangos.twinkletray"),
            ("TaskbarX", "ChrisAndri);TaskbarX"),
            ("SumatraPDF", "SumatraPDF.SumatraPDF"),
            ("Calibre", "calibre.calibre")));

        items.AddRange(BuildCategory("Communication",
            ("WhatsApp", "WhatsApp.WhatsApp"),
            ("Telegram Desktop", "Telegram.TelegramDesktop"),
            ("Discord", "Discord.Discord"),
            ("Zoom", "Zoom.Zoom"),
            ("Microsoft Teams", "Microsoft.Teams"),
            ("Slack", "SlackTechnologies.Slack"),
            ("Skype", "Microsoft.Skype"),
            ("Signal", "OpenWhisperSystems.Signal"),
            ("Viber", "Viber.Viber"),
            ("TeamSpeak", "TeamSpeakSystems.TeamSpeakClient"),
            ("Element", "Element.Element"),
            ("Thunderbird", "Mozilla.Thunderbird"),
            ("LINE", "LINE.LINE"),
            ("WeChat", "Tencent.WeChat"),
            ("Mailspring", "Foundry376.Mailspring"),
            ("Jitsi Meet", "Jitsi.Meet"),
            ("Wire", "Wire.Wire"),
            ("Mattermost Desktop", "Mattermost.MattermostDesktop"),
            ("Ferdium", "Ferdium.Ferdium"),
            ("Beeper", "Beeper.Beeper"),
            ("Pidgin", "Pidgin.Pidgin"),
            ("BlueMail", "BlueMail.BlueMail"),
            ("Revolt", "Revolt.RevoltDesktop"),
            ("Session", "Oxen.Session"),
            ("Tutanota", "Tutanota.Tutanota"),
            ("Briar", "Briar.Briar"),
            ("SimpleX Chat", "SimpleX.SimpleXChat"),
            ("TelegramA", "AyuGram.AyuGramDesktop"),
            ("Hexchat", "HexChat.HexChat"),
            ("KMail", "KDE.KMail")));

        items.AddRange(BuildCategory("Media & Creativity",
            ("Spotify", "Spotify.Spotify"),
            ("VLC", "VideoLAN.VLC"),
            ("OBS Studio", "OBSProject.OBSStudio"),
            ("Audacity", "Audacity.Audacity"),
            ("Blender", "BlenderFoundation.Blender"),
            ("GIMP", "GIMP.GIMP"),
            ("Inkscape", "Inkscape.Inkscape"),
            ("DaVinci Resolve", "BlackmagicDesign.DaVinciResolve"),
            ("HandBrake", "HandBrake.HandBrake"),
            ("Kdenlive", "KDE.Kdenlive"),
            ("Shotcut", "Meltytech.Shotcut"),
            ("Krita", "KDE.Krita"),
            ("Paint.NET", "dotPDNLLC.paintdotnet"),
            ("Kodi", "Kodi.Kodi"),
            ("Mp3tag", "Mp3tag.Mp3tag"),
            ("ScreenToGif", "NickeManarin.ScreenToGif"),
            ("Figma", "Figma.Figma"),
            ("Canva", "Canva.Canva"),
            ("Plex", "Plex.Plex"),
            ("MusicBee", "MusicBee.MusicBee"),
            ("foobar2000", "PeterPawlowski.foobar2000"),
            ("Stremio", "Stremio.Stremio"),
            ("mpv", "mpv.net"),
            ("IrfanView", "IrfanSkiljan.IrfanView"),
            ("XnView MP", "XnSoft.XnViewMP"),
            ("Olive Video Editor", "OliveTeam.OliveVideoEditor"),
            ("Lossless Cut", "MifiLLC.LosslessCut"),
            ("PotPlayer", "Daum.PotPlayer"),
            ("MediaInfo", "MediaArea.MediaInfo.GUI"),
            ("darktable", "darktable.darktable")));

        items.AddRange(BuildCategory("Development",
            ("Visual Studio Code", "Microsoft.VisualStudioCode"),
            ("Git", "Git.Git"),
            ("Docker Desktop", "Docker.DockerDesktop"),
            ("GitHub Desktop", "GitHub.GitHubDesktop"),
            ("Postman", "Postman.Postman"),
            ("Node.js LTS", "OpenJS.NodeJS.LTS"),
            ("Python 3.12", "Python.Python.3.12"),
            ("DBeaver CE", "DBeaver.DBeaverCommunity"),
            ("Insomnia", "Kong.Insomnia"),
            ("Windows Terminal", "Microsoft.WindowsTerminal"),
            ("Neovim", "Neovim.Neovim"),
            ("VSCodium", "VSCodium.VSCodium"),
            ("WinMerge", "WinMerge.WinMerge"),
            ("Wireshark", "WiresharkFoundation.Wireshark"),
            ("DB Browser SQLite", "DBBrowserForSQLite.DBBrowserForSQLite"),
            ("pgAdmin 4", "PostgreSQL.pgAdmin"),
            ("AWS CLI", "Amazon.AWSCLI"),
            ("Azure CLI", "Microsoft.AzureCLI"),
            ("Rust", "Rustlang.Rust.GNU"),
            ("Go", "GoLang.Go"),
            ("OpenJDK 21", "EclipseAdoptium.Temurin.21.JDK"),
            ("CMake", "Kitware.CMake"),
            ("LLVM", "LLVM.LLVM"),
            ("Zig", "zig.zig"),
            ("Bun", "Oven-sh.Bun"),
            ("Deno", "DenoLand.Deno"),
            ("Notepad3", "rizonesoft.Notepad3"),
            ("HxD", "MaelHoerz.HxD"),
            ("mitmproxy", "mitmproxy.mitmproxy"),
            ("Starship", "Starship.Starship")));

        items.AddRange(BuildCategory("Gaming",
            ("Steam", "Valve.Steam"),
            ("Epic Games Launcher", "EpicGames.EpicGamesLauncher"),
            ("GOG Galaxy", "GOG.Galaxy"),
            ("Ubisoft Connect", "Ubisoft.Connect"),
            ("EA app", "ElectronicArts.EADesktop"),
            ("Riot Client", "RiotGames.RiotClient"),
            ("Battle.net", "Blizzard.BattleNet"),
            ("Minecraft Launcher", "Mojang.MinecraftLauncher"),
            ("Xbox", "Microsoft.XboxApp"),
            ("NVIDIA App", "Nvidia.NVIDIAApp"),
            ("GeForce Experience", "Nvidia.GeForceExperience"),
            ("MSI Afterburner", "Guru3D.Afterburner"),
            ("Playnite", "Playnite.Playnite"),
            ("Prism Launcher", "PrismLauncher.PrismLauncher"),
            ("OBS Studio", "OBSProject.OBSStudio"),
            ("Discord", "Discord.Discord"),
            ("CurseForge", "CurseForge.CurseForge"),
            ("Vortex", "NexusMods.Vortex"),
            ("Overwolf", "Overwolf.Overwolf"),
            ("HWiNFO", "REALiX.HWiNFO"),
            ("FurMark", "Geeks3D.FurMark"),
            ("GPU-Z", "TechPowerUp.GPU-Z"),
            ("CPU-Z", "CPUID.CPU-Z"),
            ("Moonlight", "MoonlightGameStreamingProject.Moonlight"),
            ("Sunshine", "LizardByte.Sunshine"),
            ("RetroArch", "Libretro.RetroArch"),
            ("Dolphin Emulator", "DolphinEmu.DolphinEmulator"),
            ("RivaTuner", "Guru3D.RTSS"),
            ("MangoHud", "MangoHud.MangoHud"),
            ("Samsung Magician", "Samsung.SamsungMagician")));

        items.AddRange(BuildCategory("Security & Privacy",
            ("Bitwarden", "Bitwarden.Bitwarden"),
            ("KeePassXC", "KeePassXCTeam.KeePassXC"),
            ("Malwarebytes", "Malwarebytes.Malwarebytes"),
            ("ProtonVPN", "ProtonTechnologies.ProtonVPN"),
            ("Mullvad VPN", "MullvadVPN.MullvadVPN"),
            ("Windscribe", "Windscribe.Windscribe"),
            ("WireGuard", "WireGuard.WireGuard"),
            ("VeraCrypt", "IDRIX.VeraCrypt"),
            ("Gpg4win", "GnuPG.Gpg4win"),
            ("Tor Browser", "TorProject.TorBrowser"),
            ("Brave Browser", "Brave.Brave"),
            ("Firefox", "Mozilla.Firefox"),
            ("LibreWolf", "LibreWolf.LibreWolf"),
            ("Nextcloud", "Nextcloud.NextcloudDesktop"),
            ("Cryptomator", "Skymatic.Cryptomator"),
            ("Bleachbit", "BleachBit.BleachBit"),
            ("O&O ShutUp10", "OandO.ShutUp10"),
            ("WPD", "AntibodySoftware.WPD"),
            ("SimpleWall", "AntibodySoftware.simplewall"),
            ("GlassWire", "GlassWire.GlassWire"),
            ("NetLimiter", "LockTime.NetLimiter"),
            ("Portmaster", "SafingIO.Portmaster"),
            ("AdGuard Home", "AdGuard.AdGuardHome"),
            ("Pi-hole", "PiHole.PiHole"),
            ("ClamWin", "ClamWin.ClamWin"),
            ("OpenVPN", "OpenVPNTechnologies.OpenVPN"),
            ("Authy", "Twilio.Authy"),
            ("YubiKey Manager", "Yubico.YubiKeyManager"),
            ("PrivaZer", "Goversoft.PrivaZer"),
            ("USBGuard", "USBGuard.USBGuard")));

        items.AddRange(BuildCategory("System Utilities",
            ("PowerToys", "Microsoft.PowerToys"),
            ("Everything", "voidtools.Everything"),
            ("TreeSize Free", "JAMSoftware.TreeSize.Free"),
            ("WizTree", "AntibodySoftware.WizTree"),
            ("Rufus", "Rufus.Rufus"),
            ("Ventoy", "Ventoy.Ventoy"),
            ("balenaEtcher", "Balena.Etcher"),
            ("CrystalDiskMark", "CrystalDewWorld.CrystalDiskMark"),
            ("HWMonitor", "CPUID.HWMonitor"),
            ("Speccy", "Piriform.Speccy"),
            ("Autoruns", "Microsoft.Sysinternals.Autoruns"),
            ("Process Explorer", "Microsoft.Sysinternals.ProcessExplorer"),
            ("Revo Uninstaller", "RevoUninstaller.RevoUninstaller"),
            ("Geek Uninstaller", "GeekUninstaller.GeekUninstaller"),
            ("BCUninstaller", "Klocman.BulkCrapUninstaller"),
            ("Chocolatey", "Chocolatey.Chocolatey"),
            ("WingetUI", "MartiCliment.UniGetUI"),
            ("Scoop", "ScoopInstaller.Scoop"),
            ("Dism++", "Chuyu-Team.Dism++"),
            ("NSudo", "M2Team.NsudoLG"),
            ("AutoRuns", "Microsoft.Sysinternals.Autoruns"),
            ("TCPView", "Microsoft.Sysinternals.TCPView"),
            ("Recuva", "Piriform.Recuva"),
            ("TestDisk", "CGSecurity.TestDisk"),
            ("FastCopy", "FastCopy.FastCopy"),
            ("TeraCopy", "CodeSector.TeraCopy"),
            ("FreeFileSync", "FreeFileSync.FreeFileSync"),
            ("SpaceSniffer", "Uderzo.SpaceSniffer"),
            ("Snappy Driver Installer", "Snappy-Driver-Installer.SDI"),
            ("Chris Titus WinUtil", "ChrisTitusTech.WinUtil")));

        return items;
    }

    private static IEnumerable<StoreTrendItem> BuildCategory(
        string category, params (string Name, string WingetId)[] apps)
    {
        for (var i = 0; i < apps.Length; i++)
        {
            var rank = i + 1;
            var signal = rank switch
            {
                <= 3 => "Top ranked",
                <= 10 => "Top free",
                <= 20 => "Rising",
                _ => "New"
            };

            var rating = Math.Max(3.5, Math.Round(4.9 - ((rank - 1) * 0.04), 1));
            yield return new StoreTrendItem(
                category, rank, apps[i].Name, apps[i].WingetId, rating, signal);
        }
    }
}
